general {
    base_exp_dir = ./outs/deepfashion/
    data_dir = ./data/
}

dataset {
    data_dir = ./data/deepfashion
}

train {
    message = "test"
    # dataloader的batchsize
    batch_size = 1
    # epochs len-dataset iter=epochs*len_dataset
    # epochs_all = 2000
    epochs_stage_1 =40000
    epochs_stage_2 =20000
    theta_gaussian=0.25
    theta_along_normal=0.25
    # 多少个 epoch 进行一次致密化
    densify_freq = 2000
    # 每次致密化增加点的数量
    densify_n_points = 5000
    # 从第几个 epoch 开始致密化
    densify_start_epoch = 10000
    # 允许的最大点数
    max_total_points = 100000

    datalength = 1
    # 每个get_item的点
    train_num_points = 10000
    time_sum = 5
    metric = increased
    extra_points_rate = 5
    df_filter = 0.01
    # 重建表面时候去除远点
    far = 0.015
    # 产生新点时去除远点
    outlier = 0.0035
    noise_range = 1.1
    report_freq = 100

    # load_ckpt = ckpt_040000_5epoch.pth
    load_ckpt = ckpt_040000_5epoch.pth
    learning_rate_stage1 = 0.001
    learning_rate_stage2 = 0.001
    warm_up_end_stage1 = 1000
    warm_up_end_stage2 = 500

}

model {
    udf_network {
        d_out = 1
        d_in = 3
        d_hidden = 256
        n_layers = 12
        skip_in = [4,8]
        film_in = [3,7]
        multires=5
        bias = 0.5
        scale = 1.0
        geometric_init = True
        weight_norm = True
    }

}

